seed: 42
task_type: sc

do_train: True
do_predict: True
pipeline: False 

num_train_epochs: 6
max_seq_length: 80
dataloader_num_workers: 2

per_device_train_batch_size: 32
per_device_eval_batch_size: 32 
gradient_accumulation_steps: 2
learning_rate: 3.0e-5
weight_decay: 1.0e-5
warmup_ratio: 0.1 
max_grad_norm: 1
optim: adamw_torch

load_best_model_at_end: True
metric_for_best_model: accuracy 
greater_is_better: True 

logging_strategy: steps
logging_steps: 100
evaluation_strategy: epoch
eval_steps: 500
save_strategy: epoch
save_steps: 500


